### ISSUE TITLE
Checking event emitted without specifying expected args

### ISSUE THREAD

**Issue by viva-network** [chaintrust/truffle-test-utils#2]
Hi, it seems mandatory to specify expected args to test that an event was emitted. Is it possible for this to be optional? Some events are difficult to determine the args for in advance. Great tool and thanks for sharing.

**Comment by phbernard** [comment]
That's right! In the next version you will be able to do:

    let result = await testedSmartContract.testedFunction();
    assert.web3Event(result, {
      event: 'TestedEvent'
      // Any argument is allowed
    }, 'The event is emitted');

**Comment by phbernard** [comment]
Available in 0.1.0, published a minute ago.
