### ISSUE TITLE
Checking an event was emitted without checking all events

### ISSUE THREAD

**Issue by viva-network** [chaintrust/truffle-test-utils#3]
Seems that I cannot verify that a single event among many was emitted. Some events are not necessary to verify emitted properly (looking for a particular one).

**Comment by phbernard** [comment]
You can now use `web3SomeEvents`, whereas `web3AllEvents` implements the old behavior. And `web3Events` is an alias to  `web3AllEvents` for backward compatibility.

Available in 0.1.0, published a minute ago.
